/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Janis Zeps (https://sketchfab.com/zeps9001)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/antique-movie-camera-e3bfab76da80435fa5af1d8e0b1f2b17
Title: Antique Movie Camera
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Camera(props) {
  const { nodes, materials } = useGLTF( import.meta.env.BASE_URL + 'models/antique_movie_camera (1).glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.camera_Camera_0.geometry}
          material={materials.Camera}
          position={[-4.1, 0.052, -17.143]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload( import.meta.env.BASE_URL + 'models/antique_movie_camera (1).glb')
